[package]
authors = ["Alexandr Shalugin <shalugin.alexandr@gmail.com>"]
name = "rust-experiment"
version = "0.1.0"

[dependencies]
file = "1.1.1"
rand = "0.3.15"
rocket = "0.2.6"
rocket_codegen = "0.2.6"
